- hosts: all
  tasks:
  - name: Create multiple directories
    file: 
      path: '{{item}}' 
      state: absent 
      mode: 0775 
      owner: patrick 
      group: patrick
    with_items:
    - '/tmp/dir1'
    - '/tmp/dir2'
    - '/tmp/dir3'
